version: '3.8'

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["npm", "run", "start:dev"]
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@database:5432/mydb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app_network

  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
